frase = 'Curso em Vídeo Python'
print(frase)
print(frase[3])
print(frase[:14])
print(frase[14:])
print(frase[1:15:2])
print(frase[::2])
print(frase.count('o'))
print(frase.__len__())
print(len(frase))
print(frase.replace('Python','Android'))
print('Curso'in frase)
print(frase.find('Python'))
print(frase.split())